// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package datagen

import (
	"time"

	"github.com/google/uuid"
	null_v4 "gopkg.in/guregu/null.v4"
)

type SocialPreference struct {
	ProfileID uuid.UUID   `json:"profile_id"`
	AgeFrom   null_v4.Int `json:"age_from"`
	AgeTo     null_v4.Int `json:"age_to"`
	Raduis    null_v4.Int `json:"raduis"`
}

type SocialProfile struct {
	ID          uuid.UUID      `json:"id"`
	Version     int64          `json:"version"`
	Email       string         `json:"email"`
	PhoneNumber null_v4.String `json:"phone_number"`
	Username    string         `json:"username"`
	Password    string         `json:"password"`
	Name        string         `json:"name"`
	Birthday    time.Time      `json:"birthday"`
	Gender      int16          `json:"gender"`
	Longitude   null_v4.Float  `json:"longitude"`
	Latitude    null_v4.Float  `json:"latitude"`
	LikeTtl     int16          `json:"like_ttl"`
}
