// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package datagen

import (
	"context"
	"time"

	"github.com/google/uuid"
	null_v4 "gopkg.in/guregu/null.v4"
)

const createProfile = `-- name: CreateProfile :one
INSERT INTO social.profiles (birthday, email, name, username, password, gender, longitude, latitude, phone_number) VALUES ($1::date, $2::varchar(320), $3::varchar(50), $4::varchar(30), $5::varchar(250), $6::smallint, $7::real, $8::real, $9::varchar(15)) RETURNING id, version, email, phone_number, username, password, name, birtday, gender, longitude, latitude, like_ttl
`

type CreateProfileParams struct {
	Birthday    time.Time      `json:"birthday"`
	Email       string         `json:"email"`
	Name        string         `json:"name"`
	Username    string         `json:"username"`
	Password    string         `json:"password"`
	Gender      int16          `json:"gender"`
	Longitude   null_v4.Float  `json:"longitude"`
	Latitude    null_v4.Float  `json:"latitude"`
	PhoneNumber null_v4.String `json:"phone_number"`
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (SocialProfile, error) {
	row := q.db.QueryRowContext(ctx, createProfile,
		arg.Birthday,
		arg.Email,
		arg.Name,
		arg.Username,
		arg.Password,
		arg.Gender,
		arg.Longitude,
		arg.Latitude,
		arg.PhoneNumber,
	)
	var i SocialProfile
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.Email,
		&i.PhoneNumber,
		&i.Username,
		&i.Password,
		&i.Name,
		&i.Birtday,
		&i.Gender,
		&i.Longitude,
		&i.Latitude,
		&i.LikeTtl,
	)
	return i, err
}

const getProfileByEmail = `-- name: GetProfileByEmail :one
SELECT id FROM social.profiles
WHERE email=$1
`

func (q *Queries) GetProfileByEmail(ctx context.Context, email string) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getProfileByEmail, email)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const updatePreferences = `-- name: UpdatePreferences :one
UPDATE social.preferences
SET
    age_from = COALESCE($1::smallint, latitude),
    age_to = COALESCE($2::smallint, latitude),
    radius = COALESCE($3::int, latitude)
WHERE profile_id=$4::uuid RETURNING profile_id, age_from, age_to, raduis
`

type UpdatePreferencesParams struct {
	AgeFrom   null_v4.Int `json:"age_from"`
	AgeTo     null_v4.Int `json:"age_to"`
	Radius    null_v4.Int `json:"radius"`
	ProfileID uuid.UUID   `json:"profile_id"`
}

func (q *Queries) UpdatePreferences(ctx context.Context, arg UpdatePreferencesParams) (SocialPreference, error) {
	row := q.db.QueryRowContext(ctx, updatePreferences,
		arg.AgeFrom,
		arg.AgeTo,
		arg.Radius,
		arg.ProfileID,
	)
	var i SocialPreference
	err := row.Scan(
		&i.ProfileID,
		&i.AgeFrom,
		&i.AgeTo,
		&i.Raduis,
	)
	return i, err
}

const updateProfile = `-- name: UpdateProfile :one
UPDATE social.profiles
SET
    birthday = COALESCE($1::date, birthday),
    name = COALESCE($2::varchar(50), name),
    phone_number = COALESCE($3::varchar(15), phone_number),
    username = COALESCE($4::varchar(30), username),
    longitude = COALESCE($5::real, longitude),
    latitude = COALESCE($6::real, latitude),
    like_ttl = COALESCE($7::smallint, like_ttl) RETURNING id, version, email, phone_number, username, password, name, birtday, gender, longitude, latitude, like_ttl
`

type UpdateProfileParams struct {
	Birthday    null_v4.Time   `json:"birthday"`
	Name        null_v4.String `json:"name"`
	PhoneNumber null_v4.String `json:"phone_number"`
	Username    null_v4.String `json:"username"`
	Longitude   null_v4.Float  `json:"longitude"`
	Latitude    null_v4.Float  `json:"latitude"`
	LikeTtl     null_v4.Int    `json:"like_ttl"`
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) (SocialProfile, error) {
	row := q.db.QueryRowContext(ctx, updateProfile,
		arg.Birthday,
		arg.Name,
		arg.PhoneNumber,
		arg.Username,
		arg.Longitude,
		arg.Latitude,
		arg.LikeTtl,
	)
	var i SocialProfile
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.Email,
		&i.PhoneNumber,
		&i.Username,
		&i.Password,
		&i.Name,
		&i.Birtday,
		&i.Gender,
		&i.Longitude,
		&i.Latitude,
		&i.LikeTtl,
	)
	return i, err
}
