// Code generated by MockGen. DO NOT EDIT.
// Source: internal/interfaces/repo/profile.go

// Package mock_repo is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entities "github.com/London57/profiles/internal/data/entities"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockProfilesRepo is a mock of ProfilesRepo interface.
type MockProfilesRepo struct {
        ctrl     *gomock.Controller
        recorder *MockProfilesRepoMockRecorder
}

// MockProfilesRepoMockRecorder is the mock recorder for MockProfilesRepo.
type MockProfilesRepoMockRecorder struct {
        mock *MockProfilesRepo
}

// NewMockProfilesRepo creates a new mock instance.
func NewMockProfilesRepo(ctrl *gomock.Controller) *MockProfilesRepo {
        mock := &MockProfilesRepo{ctrl: ctrl}
        mock.recorder = &MockProfilesRepoMockRecorder{mock}
        return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProfilesRepo) EXPECT() *MockProfilesRepoMockRecorder {
        return m.recorder
}

// AddPreferences mocks base method.
func (m *MockProfilesRepo) AddPreferences(arg0 context.Context, arg1 entities.ProfileEntity) {
        m.ctrl.T.Helper()
        m.ctrl.Call(m, "AddPreferences", arg0, arg1)
}

// AddPreferences indicates an expected call of AddPreferences.
func (mr *MockProfilesRepoMockRecorder) AddPreferences(arg0, arg1 interface{}) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPreferences", reflect.TypeOf((*MockProfilesRepo)(nil).AddPreferences), arg0, arg1)
}

// CreateProfile mocks base method.
func (m *MockProfilesRepo) CreateProfile(arg0 context.Context, arg1 entities.ProfileEntity) (*entities.ProfileEntity, error) {    
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "CreateProfile", arg0, arg1)
        ret0, _ := ret[0].(*entities.ProfileEntity)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// CreateProfile indicates an expected call of CreateProfile.
func (mr *MockProfilesRepoMockRecorder) CreateProfile(arg0, arg1 interface{}) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProfile", reflect.TypeOf((*MockProfilesRepo)(nil).CreateProfile), arg0, arg1)
}

// GetProfileIdByEmail mocks base method.
func (m *MockProfilesRepo) GetProfileIdByEmail(arg0 context.Context, arg1 string) (uuid.UUID, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "GetProfileIdByEmail", arg0, arg1)
        ret0, _ := ret[0].(uuid.UUID)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// GetProfileIdByEmail indicates an expected call of GetProfileIdByEmail.
func (mr *MockProfilesRepoMockRecorder) GetProfileIdByEmail(arg0, arg1 interface{}) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfileIdByEmail", reflect.TypeOf((*MockProfilesRepo)(nil).GetProfileIdByEmail), arg0, arg1)
}

// UpdateProfile mocks base method.
func (m *MockProfilesRepo) UpdateProfile(arg0 context.Context, arg1 map[string]any) (*entities.ProfileEntity, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "UpdateProfile", arg0, arg1)
        ret0, _ := ret[0].(*entities.ProfileEntity)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// UpdateProfile indicates an expected call of UpdateProfile.
func (mr *MockProfilesRepoMockRecorder) UpdateProfile(arg0, arg1 interface{}) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProfile", reflect.TypeOf((*MockProfilesRepo)(nil).UpdateProfile), arg0, arg1)
}